### ISSUE TITLE
Account service address not found

### ISSUE THREAD

**Issue by ghost** [Magora-IOS/sheet-localization#1]
Hello, I have been doing all your steps, but when I tried share sheet access for client email - had same result:

Your message wasn't delivered to localizesample@localizesample.iam.gserviceaccount.combecause the domain localizesample.iam.gserviceaccount.comcouldn't be found. Check for typos or unnecessary spaces and try again. 

The response was:
DNS Error: 15388180 DNS type 'mx' lookup of localizesample.iam.gserviceaccount.com responded with code NXDOMAIN Domain name not found: localizesample.iam.gserviceaccount.com

**Comment by kornerr** [comment]
May be registration process has been changed by Google.
It took me several hours to figure it out, so feel free to experiment.
Don't forget to report what you ended up with.

**Comment by nyeu** [comment]
Hi! I am in the same situation, any idea on how to fix it?

**Comment by kornerr** [comment]
I'm afraid you're on your own, however, feel free to share the results of your findings so that others could benefit.
